(require 'package)
(add-to-list 'package-archives '("melpa" . "http://melpa.milkbox.net/packages/"))
(package-initialize)

(defun require-package (package &optional min-version no-refresh)
  "Ask elpa to install given PACKAGE."
  (if (package-installed-p package min-version)
      t
    (if (or (assoc package package-archive-contents) no-refresh)
        (package-install package)
      (progn
        (package-refresh-contents)
        (require-package package min-version t)))))


(require-package 'json)
(require-package 'project-local-variables)
(require-package 'paredit)
(require-package 'eldoc-eval)
(require-package 'slime)
(require-package 'slime-fuzzy)
(require-package 'slime-repl)
(require-package 'gist)
(require-package 'haml-mode)
(require-package 'sass-mode)
(require-package 'markdown-mode)
(require-package 'rainbow-mode)
(require-package 'maxframe)
(require-package 'htmlize)
(require-package 'diminish)
(require-package 'autopair)
(require-package 'js-comint)
(require-package 'scratch)
(require-package 'mic-paren)
(require-package 'rainbow-delimiters)
(require-package 'marmalade)
(require-package 'session)
(require-package 'tidy)
(require-package 'whole-line-or-region)
(require-package 'ibuffer-vc)
(require-package 'coffee-mode)
(require-package 'mwe-log-commands)
(require-package 'move-text)
(require-package 'hl-sexp)
(require-package 'pointback)
(require-package 'crontab-mode)
(require-package 'regex-tool)
(require-package 'iy-go-to-char)

(provide 'init-elpa)
